#!/usr/bin/env bash
source ./scripts/create.sh
source ./scripts/delete.sh
case $1 in
  create)
    create
    exit 0
    ;;
  delete)
    delete
    exit 0
    ;;
  *)
    echo "USAGE: create|delete"
    exit 1
    ;;
esac  
