#!/usr/bin/env bash

source ./config.sh
source ./scripts/create.sh
source ./scripts/delete.sh
case $1 in
  create)
    create $2 $3
    exit 0
    ;;
  delete)
    delete $2 $3
    exit 0
    ;;
  *)
    echo "USAGE: $0 $1"
    echo ""
    create-usage
    delete-usage
    exit 1
    ;;
esac  
